@echo off
cd %cd%\adb
adb shell "su -c pm disable com.google.android.apps.wellbeing"
adb shell "su -c pm disable com.android.storagemanager"
adb shell "su -c pm disable com.android.printspooler"
adb shell "su -c pm disable com.android.wallpaper.livepicker"
adb shell "su -c pm disable com.google.android.as"
adb shell "su -c pm disable com.google.android.tts"
adb shell "su -c pm disable com.android.bookmarkprovider"
adb shell "su -c pm disable com.android.emergency"
adb shell "su -c pm disable com.google.android.gms.location.history"
adb shell "su -c pm disable com.google.android.feedback"
adb shell "su -c pm disable org.omnirom.omnijaws"
adb shell "su -c pm disable com.android.managedprovisioning"
adb shell "su -c pm disable com.google.android.projection.gearhead"
adb shell "su -c pm disable com.android.dreams.phototable"
adb shell "su -c pm disable com.google.android.googlequicksearchbox"
adb shell "su -c pm disable com.android.bips"
adb shell "su -c pm disable com.google.android.setupwizard"
adb shell "su -c pm disable com.android.apps.tag"
adb shell "su -c pm disable android.romstats"
adb shell "su -c pm disable com.android.providers.calendar"
adb shell "su -c pm disable com.tencent.soter.soterserver"
adb shell "su -c pm disable com.android.cellbroadcastreceiver.module"
adb shell "su -c pm disable com.android.providers.downloads.ui"
adb shell "su -c pm disable com.google.android.apps.pixelmigrate"
adb shell "su -c pm disable com.google.android.calendar"
adb shell "su -c pm disable android.romstats"
adb shell "su -c pm disable com.android.calendar"
adb shell "su -c pm disable com.android.dreams.basic"
adb shell "su -c pm disable com.android.hotwordenrollment.okgoogle"
adb shell "su -c pm disable com.android.mms.service"
adb shell "su -c pm disable com.android.mms"
adb shell "su -c pm disable com.android.wallpaper.livepicker"
adb shell "su -c pm disable com.google.android.feedback"
adb shell "su -c pm disable com.google.android.marvin.talkback"
adb shell "su -c pm disable com.google.android.music"
adb shell "su -c pm disable com.google.android.printservice.recommendation"
adb shell "su -c pm disable com.google.android.syncadapters.calendar"
adb shell "su -c pm disable com.google.android.videos"
adb shell "su -c pm disable com.google.ar.lens"
adb shell "su -c pm disable com.mi.globalTrendNews"
adb shell "su -c pm disable com.mi.webkit.core"
adb shell "su -c pm disable com.mipay.wallet.id"
adb shell "su -c pm disable com.mipay.wallet.in"
adb shell "su -c pm disable com.miui.analytics"
adb shell "su -c pm disable com.miui.bugreport"
adb shell "su -c pm disable com.miui.extraphoto"
adb shell "su -c pm disable com.miui.fm"
adb shell "su -c pm disable com.miui.fmservice"
adb shell "su -c pm disable com.miui.freeform"
adb shell "su -c pm disable com.miui.hybrid"
adb shell "su -c pm disable com.miui.hybrid.accessory"
adb shell "su -c pm disable com.miui.mishare.connectivity"
adb shell "su -c pm disable com.miui.miwallpaper.mars"
adb shell "su -c pm disable com.miui.miwallpaper.earth"
adb shell "su -c pm disable com.miui.msa.global"
adb shell "su -c pm disable com.miui.nextpay"
adb shell "su -c pm disable com.miui.phrase"
adb shell "su -c pm disable com.miui.smsextra"
adb shell "su -c pm disable com.miui.yellowpage"
adb shell "su -c pm disable com.miui.wmsvc"
adb shell "su -c pm disable com.xiaomi.joyose"
adb shell "su -c pm disable com.xiaomi.glgm"
adb shell "su -c pm disable com.xiaomi.midrop"
adb shell "su -c pm disable com.xiaomi.mircs"
adb shell "su -c pm disable com.xiaomi.payment"
adb shell "su -c pm disable com.xiaomi.simactivate.service"
cls
echo "____________________________________________________________"
echo "|      ____       __    __            __           __   __ |"
echo "|     / __ \___  / /_  / /___  ____ _/ /____  ____/ /  / / |"
echo "|    / / / / _ \/ __ \/ / __ \/ __ `/ __/ _ \/ __  /  / /  |"
echo "|   / /_/ /  __/ /_/ / / /_/ / /_/ / /_/  __/ /_/ /  /_/   |"
echo "|  /_____/\___/_.___/_/\____/\__,_/\__/\___/\__,_/  (_)    |"
echo "|__________________________________________________________|"
echo "|                Made by @Siimsek on Telegram              |"

pause
