@echo off
cd %cd%\adb
adb shell pm enable-user --user 0 android.romstats
adb shell pm enable-user --user 0 com.android.apps.tag
adb shell pm enable-user --user 0 com.android.bips
adb shell pm enable-user --user 0 com.android.bookmarkprovider
adb shell pm enable-user --user 0 com.android.calculator2
adb shell pm enable-user --user 0 com.android.calendar
adb shell pm enable-user --user 0 com.android.cellbroadcastreceiver.module
adb shell pm enable-user --user 0 com.android.chrome
adb shell pm enable-user --user 0 com.android.dreams.basic
adb shell pm enable-user --user 0 com.android.dreams.phototable
adb shell pm enable-user --user 0 com.android.email
adb shell pm enable-user --user 0 com.android.emergency
adb shell pm enable-user --user 0 com.android.exchange
adb shell pm enable-user --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm enable-user --user 0 com.android.managedprovisioning
adb shell pm enable-user --user 0 com.android.mms
adb shell pm enable-user --user 0 com.android.mms.service
adb shell pm enable-user --user 0 com.android.printspooler
adb shell pm enable-user --user 0 com.android.providers.calendar
adb shell pm enable-user --user 0 com.android.providers.downloads.ui
adb shell pm enable-user --user 0 com.android.stk
adb shell pm enable-user --user 0 com.android.storagemanager
adb shell pm enable-user --user 0 com.android.wallpaper.livepicker
adb shell pm enable-user --user 0 com.caf.fmradio
adb shell pm enable-user --user 0 com.cherish.updater
adb shell pm enable-user --user 0 com.duckduckgo.mobile.android
adb shell pm enable-user --user 0 com.google.android.accessibility.soundamplifier
adb shell pm enable-user --user 0 com.google.android.apps.docs
adb shell pm enable-user --user 0 com.google.android.apps.helprtc
adb shell pm enable-user --user 0 com.google.android.apps.nbu.files
adb shell pm enable-user --user 0 com.google.android.apps.pixelmigrate
adb shell pm enable-user --user 0 com.google.android.apps.restore
adb shell pm enable-user --user 0 com.google.android.apps.safetyhub
adb shell pm enable-user --user 0 com.google.android.apps.turbo
adb shell pm enable-user --user 0 com.google.android.apps.wearables.maestro.companion
adb shell pm enable-user --user 0 com.google.android.apps.wellbeing
adb shell pm enable-user --user 0 com.google.android.as
adb shell pm enable-user --user 0 com.google.android.calendar
adb shell pm enable-user --user 0 com.google.android.feedback
adb shell pm enable-user --user 0 com.google.android.gms.location.history
adb shell pm enable-user --user 0 com.google.android.googlequicksearchbox
adb shell pm enable-user --user 0 com.google.android.marvin.talkback
adb shell pm enable-user --user 0 com.google.android.music
adb shell pm enable-user --user 0 com.google.android.pixel.setupwizard
adb shell pm enable-user --user 0 com.google.android.printservice.recommendation
adb shell pm enable-user --user 0 com.google.android.projection.gearhead
adb shell pm enable-user --user 0 com.google.android.setupwizard
adb shell pm enable-user --user 0 com.google.android.syncadapters.calendar
adb shell pm enable-user --user 0 com.google.android.tag
adb shell pm enable-user --user 0 com.google.android.tts
adb shell pm enable-user --user 0 com.google.android.videos
adb shell pm enable-user --user 0 com.google.ar.lens
adb shell pm enable-user --user 0 com.google.audio.hearing.visualization.accessibility.scribe
adb shell pm enable-user --user 0 com.mi.globalTrendNews
adb shell pm enable-user --user 0 com.mi.webkit.core
adb shell pm enable-user --user 0 com.mipay.wallet.id
adb shell pm enable-user --user 0 com.mipay.wallet.in
adb shell pm enable-user --user 0 com.miui.analytics
adb shell pm enable-user --user 0 com.miui.bugreport
adb shell pm enable-user --user 0 com.miui.extraphoto
adb shell pm enable-user --user 0 com.miui.fm
adb shell pm enable-user --user 0 com.miui.fmservice
adb shell pm enable-user --user 0 com.miui.freeform
adb shell pm enable-user --user 0 com.miui.hybrid
adb shell pm enable-user --user 0 com.miui.hybrid.accessory
adb shell pm enable-user --user 0 com.miui.mishare.connectivity
adb shell pm enable-user --user 0 com.miui.miwallpaper.earth
adb shell pm enable-user --user 0 com.miui.miwallpaper.mars
adb shell pm enable-user --user 0 com.miui.msa.global
adb shell pm enable-user --user 0 com.miui.nextpay
adb shell pm enable-user --user 0 com.miui.phrase
adb shell pm enable-user --user 0 com.miui.smsextra
adb shell pm enable-user --user 0 com.miui.wmsvc
adb shell pm enable-user --user 0 com.miui.yellowpage
adb shell pm enable-user --user 0 com.samsung.android.app.episodes
adb shell pm enable-user --user 0 com.samsung.android.app.ledcoverdream
adb shell pm enable-user --user 0 com.samsung.android.app.memo
adb shell pm enable-user --user 0 com.samsung.android.app.storyalbumwidget
adb shell pm enable-user --user 0 com.samsung.android.app.vrsetupwizardstub
adb shell pm enable-user --user 0 com.samsung.android.email.provider
adb shell pm enable-user --user 0 com.samsung.android.hmt.vrshell
adb shell pm enable-user --user 0 com.samsung.android.hmt.vrsvc
adb shell pm enable-user --user 0 com.samsung.android.service.travel
adb shell pm enable-user --user 0 com.samsung.android.spay
adb shell pm enable-user --user 0 com.samsung.android.tripwidget
adb shell pm enable-user --user 0 com.samsung.android.voicewakeup
adb shell pm enable-user --user 0 com.samsung.groupcast
adb shell pm enable-user --user 0 com.samsung.voiceserviceplatform
adb shell pm enable-user --user 0 com.sec.android.app.desktoplauncher
adb shell pm enable-user --user 0 com.sec.android.app.gamehub
adb shell pm enable-user --user 0 com.sec.android.app.ocr
adb shell pm enable-user --user 0 com.sec.android.app.translator
adb shell pm enable-user --user 0 com.sec.android.app.withtv
adb shell pm enable-user --user 0 com.sec.android.cover.ledcover
adb shell pm enable-user --user 0 com.sec.android.service.health
adb shell pm enable-user --user 0 com.sec.android.sidesync30
adb shell pm enable-user --user 0 com.sec.android.widgetapp.diotek.smemo
adb shell pm enable-user --user 0 com.sec.everglades
adb shell pm enable-user --user 0 com.sec.everglades.update
adb shell pm enable-user --user 0 com.sec.kidsplat.installer
adb shell pm enable-user --user 0 com.sec.readershub
adb shell pm enable-user --user 0 com.sec.spp.push
adb shell pm enable-user --user 0 com.sec.yosemite.phone
adb shell pm enable-user --user 0 com.tencent.soter.soterserver
adb shell pm enable-user --user 0 com.tripadvisor.tripadvisor
adb shell pm enable-user --user 0 com.vlingo.midas
adb shell pm enable-user --user 0 com.xiaomi.glgm
adb shell pm enable-user --user 0 com.xiaomi.joyose
adb shell pm enable-user --user 0 com.xiaomi.midrop
adb shell pm enable-user --user 0 com.xiaomi.mircs
adb shell pm enable-user --user 0 com.xiaomi.payment
adb shell pm enable-user --user 0 com.xiaomi.simactivate.service
adb shell pm enable-user --user 0 io.chaldeaprjkt.gamespace
adb shell pm enable-user --user 0 org.lineageos.audiofx
adb shell pm enable-user --user 0 org.lineageos.eleven
adb shell pm enable-user --user 0 org.lineageos.etar
adb shell pm enable-user --user 0 org.lineageos.jelly
adb shell pm enable-user --user 0 org.lineageos.updater
adb shell pm enable-user --user 0 org.omnirom.logcat
adb shell pm enable-user --user 0 org.omnirom.omnijaws
adb shell pm enable-user --user 0 tv.peel.samsung.app

cls
echo done