@echo off
cd %cd%\adb
adb shell "su -c pm enable com.google.android.apps.wellbeing"
adb shell "su -c pm enable com.android.storagemanager"
adb shell "su -c pm enable com.android.printspooler"
adb shell "su -c pm enable com.android.wallpaper.livepicker"
adb shell "su -c pm enable com.google.android.as"
adb shell "su -c pm enable com.google.android.tts"
adb shell "su -c pm enable com.android.bookmarkprovider"
adb shell "su -c pm enable com.android.emergency"
adb shell "su -c pm enable com.google.android.gms.location.history"
adb shell "su -c pm enable com.google.android.feedback"
adb shell "su -c pm enable org.omnirom.omnijaws"
adb shell "su -c pm enable com.android.managedprovisioning"
adb shell "su -c pm enable com.google.android.projection.gearhead"
adb shell "su -c pm enable com.android.dreams.phototable"
adb shell "su -c pm enable com.google.android.googlequicksearchbox"
adb shell "su -c pm enable com.android.bips"
adb shell "su -c pm enable com.google.android.setupwizard"
adb shell "su -c pm enable com.android.apps.tag"
adb shell "su -c pm enable android.romstats"
adb shell "su -c pm enable com.android.providers.calendar"
adb shell "su -c pm enable com.tencent.soter.soterserver"
adb shell "su -c pm enable com.android.cellbroadcastreceiver.module"
adb shell "su -c pm enable com.android.providers.downloads.ui"
adb shell "su -c pm enable com.google.android.apps.pixelmigrate"
adb shell "su -c pm enable com.google.android.calendar"
adb shell "su -c pm enable android.romstats"
adb shell "su -c pm enable com.android.calendar"
adb shell "su -c pm enable com.android.dreams.basic"
adb shell "su -c pm enable com.android.hotwordenrollment.okgoogle"
adb shell "su -c pm enable com.android.mms.service"
adb shell "su -c pm enable com.android.mms"
adb shell "su -c pm enable com.android.wallpaper.livepicker"
adb shell "su -c pm enable com.google.android.feedback"
adb shell "su -c pm enable com.google.android.marvin.talkback"
adb shell "su -c pm enable com.google.android.music"
adb shell "su -c pm enable com.google.android.printservice.recommendation"
adb shell "su -c pm enable com.google.android.syncadapters.calendar"
adb shell "su -c pm enable com.google.android.videos"
adb shell "su -c pm enable com.google.ar.lens"
adb shell "su -c pm enable com.mi.globalTrendNews"
adb shell "su -c pm enable com.mi.webkit.core"
adb shell "su -c pm enable com.mipay.wallet.id"
adb shell "su -c pm enable com.mipay.wallet.in"
adb shell "su -c pm enable com.miui.analytics"
adb shell "su -c pm enable com.miui.bugreport"
adb shell "su -c pm enable com.miui.extraphoto"
adb shell "su -c pm enable com.miui.fm"
adb shell "su -c pm enable com.miui.fmservice"
adb shell "su -c pm enable com.miui.freeform"
adb shell "su -c pm enable com.miui.hybrid"
adb shell "su -c pm enable com.miui.hybrid.accessory"
adb shell "su -c pm enable com.miui.mishare.connectivity"
adb shell "su -c pm enable com.miui.miwallpaper.mars"
adb shell "su -c pm enable com.miui.miwallpaper.earth"
adb shell "su -c pm enable com.miui.msa.global"
adb shell "su -c pm enable com.miui.nextpay"
adb shell "su -c pm enable com.miui.phrase"
adb shell "su -c pm enable com.miui.smsextra"
adb shell "su -c pm enable com.miui.yellowpage"
adb shell "su -c pm enable com.miui.wmsvc"
adb shell "su -c pm enable com.xiaomi.joyose"
adb shell "su -c pm enable com.xiaomi.glgm"
adb shell "su -c pm enable com.xiaomi.midrop"
adb shell "su -c pm enable com.xiaomi.mircs"
adb shell "su -c pm enable com.xiaomi.payment"
adb shell "su -c pm enable com.xiaomi.simactivate.service"
adb shell "su -c pm enable com.samsung.android.email.provider"
adb shell "su -c pm enable com.samsung.android.app.ledcoverdream"
adb shell "su -c pm enable com.sec.android.cover.ledcover"
adb shell "su -c pm enable com.sec.android.app.desktoplauncher"
adb shell "su -c pm enable com.sec.android.app.withtv"
adb shell "su -c pm enable com.samsung.android.app.memo"
adb shell "su -c pm enable com.sec.spp.push"
adb shell "su -c pm enable com.samsung.android.spay"
adb shell "su -c pm enable com.samsung.android.voicewakeup"
adb shell "su -c pm enable com.samsung.voiceserviceplatform"
adb shell "su -c pm enable com.sec.android.sidesync30"
adb shell "su -c pm enable com.samsung.android.hmt.vrsvc"
adb shell "su -c pm enable com.samsung.android.app.vrsetupwizardstub"
adb shell "su -c pm enable com.samsung.android.hmt.vrshell"
adb shell "su -c pm enable com.android.exchange"
adb shell "su -c pm enable com.samsung.groupcast"
adb shell "su -c pm enable com.sec.android.service.health"
adb shell "su -c pm enable com.sec.kidsplat.installer"
adb shell "su -c pm enable com.sec.android.widgetapp.diotek.smemo"
adb shell "su -c pm enable com.sec.android.app.translator"
adb shell "su -c pm enable com.vlingo.midas"
adb shell "su -c pm enable com.sec.readershub"
adb shell "su -c pm enable com.sec.android.app.gamehub"
adb shell "su -c pm enable com.sec.everglades.update"
adb shell "su -c pm enable com.sec.everglades"
adb shell "su -c pm enable tv.peel.samsung.app"
adb shell "su -c pm enable com.sec.yosemite.phone"
adb shell "su -c pm enable com.samsung.android.app.episodes"
adb shell "su -c pm enable com.samsung.android.app.storyalbumwidget"
adb shell "su -c pm enable com.samsung.android.tripwidget"
adb shell "su -c pm enable com.samsung.android.service.travel"
adb shell "su -c pm enable com.tripadvisor.tripadvisor"
adb shell "su -c pm enable com.android.email"
adb shell "su -c pm enable com.sec.android.app.ocr"
cls
echo "____________________________________________________________"
echo "|      ____       __    __            __           __   __ |"
echo "|     / __ \___  / /_  / /___  ____ _/ /____  ____/ /  / / |"
echo "|    / / / / _ \/ __ \/ / __ \/ __ `/ __/ _ \/ __  /  / /  |"
echo "|   / /_/ /  __/ /_/ / / /_/ / /_/ / /_/  __/ /_/ /  /_/   |"
echo "|  /_____/\___/_.___/_/\____/\__,_/\__/\___/\__,_/  (_)    |"
echo "|__________________________________________________________|"
echo "|                Made by @Siimsek on Telegram              |"
pause
